#!/usr/bin/env bash

# -----------------------------------------------------------------------------
# FILE:         build_vm.sh
# AUTHOR:       Aiden Kimmerling <apkimmerling@gmail.com>
# CREATED:      07-23-2026
# LAST EDITED:  07-23-2026
# DESCRIPTION:  Builds a ROS2-ready Ubuntu Desktop virtual machine using UTM,
#               a hypervisor for macOS. It is used in tandem with an autoinstall
#               file --- used for installing all packages --- and a helper script,
#               which is used to generate and configure the virtual machine and
#               its settings. It is intended to only be used for macOS users
#               wanting to develop for ROS2 on their own laptops Additionally, 
#               this script requires a newer Mac (2019+), as it assumes an 
#               ARM-based processor (M-Series MacBooks).
# USAGE:        ./build_vm.sh [options]
# OPTIONS:      Run `./build_vm.sh --help` for list of options
# DEPENDS:      macOS, bash, AppleScript, UTM
# LICENSE:      Apache 2.0
# -----------------------------------------------------------------------------

# ------------------------------------------------------------------
# Default variables and constants
# ------------------------------------------------------------------
UBUNTU_DISTRO=noble
ROS_DISTRO=jazzy
VM_NAME=""
USERNAME="workstation"

CORES=0
DISK_GB=32
MEMORY_MB=5120 # 5GiB
DISP_RES=3456x2160 # Screen resolution of MacBook Pro 2024

DELETE_ISO=true
OPEN_VM=true
REBOOT_VM=true
DELETE_EXISTING_VM=false
BASE_ROS_ONLY=false

VM_NOTES="ROS2-Ready Ubuntu Virtual Machine generated by UNL-Lunabotics build_vm script"

SCRIPT_DIR="resources/scripts"
CONFIG_DIR="resources/config"

WORKDIR=$(mktemp -d)

# ------------------------------------------------------------------
# Get the Ubuntu Version (i.e. 24.04) from the ubuntu distro
# ------------------------------------------------------------------
find_ubuntu_release() {
  UBUNTU_RELEASE=$(curl -fsSL https://changelogs.ubuntu.com/meta-release |
    awk -v c="${UBUNTU_DISTRO}" '/^Dist:/ { d=$2 }  d==c && /^Version:/ { print $2; exit }')
}

# ------------------------------------------------------------------
# Substitutes environment vars in files with their values
# macOS does not ship with the proper `envsubst` command,
# so use this as a sort of fallback
# ------------------------------------------------------------------
envsubst() { eval "echo \"$(sed 's/"/\\"/g')\""; }

# ------------------------------------------------------------------
# Downloads a public GPG key and sets it to an environment variable
# ------------------------------------------------------------------
make_apt_key() {
  local var_name="$1"
  local url="$2"

  # Downloads $url to a file
  curl -L -o "${WORKDIR}/${var_name}" "$url"

  # Sets $var_name to the contents of the downloaded file, with proper indenting
  printf -v "$var_name" '%s' "$(sed '2,$s/^/          /' < "${WORKDIR}/${var_name}")"
}

find_ubuntu_release

usage() {
echo \
"Usage: $(basename "$0") [OPTIONS]

Options:
  -u, --ubuntu DISTRO            Ubuntu release. Match with ROS distro (default: ${UBUNTU_DISTRO})
  -r, --ros DISTRO               ROS 2 distribution. Match with Ubuntu distro (default: ${ROS_DISTRO})
  -n, --name NAME                Virtual machine name (default Ubuntu ${UBUNTU_RELEASE} ARM64)
  -U, --username USERNAME        Username for the VM (default: ${USERNAME})
  -s, --size GB                  Disk size in GB (default: ${DISK_GB})
  -m, --memory MiB               Memory in MiB (default: ${MEMORY_MB})
  -c, --cores COUNT              Number of CPU cores (default: ${CORES} = let UTM decide)
  -R, --resolution WIDTHxHEIGHT  Display resolution (default: ${DISP_RES})
      --base-ros-only            Install only ROS Desktop; skip additional ROS packages
      --no-open                  Do not open the VM after the script completes
      --no-reboot                Do not reboot the VM after ubuntu fully installs
      --force-delete             Delete any existing virtual machine with the same name.
      --keep-iso                 Keep the downloaded ISO after the script completes
  -h, --help                     Show this help message and exit

Examples:
  $(basename "$0")
  $(basename "$0") --name UbuntuVM
  $(basename "$0") --name UbuntuVM --cores 10 --memory 12288 --keep-iso --force-delete"
}

# ------------------------------------------------------------------
# Parse flag arguments
# ------------------------------------------------------------------
while [[ $# -gt 0 ]]; do
  case "$1" in
    -u|--ubuntu) UBUNTU_DISTRO="$2"; shift 2 ;;
    -r|--ros) ROS_DISTRO="$2"; shift 2 ;;
    -n|--name) VM_NAME="$2"; shift 2 ;;
    -U|--username) USERNAME="$2"; shift 2 ;;
    -s|--size) DISK_GB="$2"; shift 2 ;;
    -m|--memory) MEMORY_MB="$2"; shift 2 ;;
    -c|--cores) CORES="$2"; shift 2 ;;
    -R|--resolution) DISP_RES="$2"; shift 2 ;;
    --base-ros-only) BASE_ROS_ONLY=true; shift ;;
    --no-open) OPEN_VM=false; shift ;;
    --no-reboot) REBOOT_VM=false; shift ;;
    --keep-iso) DELETE_ISO=false; shift ;;
    --force-delete) DELETE_EXISTING_VM=true; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1"; usage; exit 1 ;;
  esac
done

trap 'rm -rf "$WORKDIR"' EXIT

# ------------------------------------------------------------------
# Set Virtual Machine name if none is set
# ------------------------------------------------------------------
find_ubuntu_release

if [ -z "${VM_NAME}" ]; then
  VM_NAME="Ubuntu ${UBUNTU_RELEASE} ARM64"
fi

if [[ "$BASE_ROS_ONLY" != true ]]; then
  envsubst < $CONFIG_DIR/ros-packages.yaml > "$WORKDIR/ros-packages.yaml"
  OPTIONAL_ROS_PACKAGES=$(sed '2,$s/^/    /' < "$WORKDIR/ros-packages.yaml")
fi

# ------------------------------------------------------------------
# Find the Ubuntu .iso URL to download and hash to confirm
# ------------------------------------------------------------------
IMAGE_NAME=ubuntu-${UBUNTU_RELEASE}-desktop-arm64.iso
IMAGE_URL=https://cdimage.ubuntu.com/releases/${UBUNTU_DISTRO}/release/${IMAGE_NAME}
IMAGE_HASH=$(curl -fsSL https://cdimage.ubuntu.com/ubuntu/releases/${UBUNTU_DISTRO}/release/SHA256SUMS \
    | awk -v target="*${IMAGE_NAME}" '$2 == target { print $1; exit }')

# ------------------------------------------------------------------
# Download Ubuntu Desktop Image
# ------------------------------------------------------------------
mkdir -p resources/isos

ISO_PATH=resources/isos/${IMAGE_NAME}

printf "\n=== Checking if Ubuntu ${UBUNTU_RELEASE} Desktop Image is found ===\n"
if [[ ! -e "$ISO_PATH" ]] ||
   [[ $(sha256sum "$ISO_PATH" | awk '{print $1}') != "$IMAGE_HASH" ]]; then
    printf '\n=== ISO was not found or was incomplete. Downloading Ubuntu %s Desktop Image ===\n' "$UBUNTU_RELEASE"
    rm -f -- "$ISO_PATH"
    curl -L "$IMAGE_URL" -o "$ISO_PATH"
fi

cp "${ISO_PATH}" "${WORKDIR}/installer.iso"

# ------------------------------------------------------------------
# Make the Seed Image
# ------------------------------------------------------------------
printf "\n=== Making the Seed Image ===\n\n"

mkdir -p "${WORKDIR}/seed"

# Find the latest ROS APT version
ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | \
                         grep -F "tag_name" | awk -F\" '{print $4}')

# Get VSCode Key
printf "\n=== Making VSCode Repository Key ===\n"
make_apt_key VSCODE_KEY https://packages.microsoft.com/keys/microsoft.asc

# Get ROS2 Key
printf "\n=== Making ROS2 Repository Key ===\n"
make_apt_key ROS_KEY https://raw.githubusercontent.com/ros/rosdistro/refs/heads/master/ros.asc

# Subsitute template variables for real values
envsubst < $CONFIG_DIR/autoinstall.yaml > "${WORKDIR}/seed/user-data"

# Needed to make the seed image but don't need configuration
echo "hostname: ubuntu" > "${WORKDIR}/seed/meta-data"
echo "" > "${WORKDIR}/seed/network-config"

# Makes the seed image
hdiutil makehybrid -o "${WORKDIR}/seed.iso" -iso -default-volume-name cidata "${WORKDIR}/seed"

# ------------------------------------------------------------------
# Generate Virtual Machine
# ------------------------------------------------------------------
printf "\n=== Generating ${VM_NAME} Virtual Machine ===\n"

# Create the virtual machine using AppleScript
osascript "${SCRIPT_DIR}/create_utm_vm.applescript" \
  "$VM_NAME" \
  "$VM_NOTES" \
  "$CORES" \
  "$DISK_GB" \
  "$MEMORY_MB" \
  "${WORKDIR}/installer.iso" \
  "${WORKDIR}/seed.iso" \
  $OPEN_VM \
  $DELETE_EXISTING_VM

# Delete the isos folder if flag is set
if $DELETE_ISO; then
    printf "\n=== Deleting ${IMAGE_NAME} ===\n"
    rm -rf $ISO_PATH
fi

# Update virtual machine config to remove drives after successful install
if $OPEN_VM; then
  osascript "${SCRIPT_DIR}/remove_install_drives.applescript" "$VM_NAME" $REBOOT_VM
fi
