#cloud-config

runcmd:
  # Add this to force cloud-init to see this file
  - [eval, subiquity.autoinstallpath=/autoinstall.yaml]

autoinstall:
  version: 1

  source:
    id: ubuntu-server

  # Ensures there is an active network connection
  network:
    version: 2
    ethernets:
      default:
        match:
          name: ${NETWORK_INTERFACE}
        dhcp4: true

  # Set user 'workstation'
  identity:
    username: workstation
    hostname: ubuntu
    password: "${PASS_HASH}"

  # Install packages
  packages:
    # Start from server so install desktop
    - ubuntu-desktop

    # Enable Clipboard Sharing
    - spice-vdagent

    # Use network-manager instead of systemd.networkd
    - network-manager
    - cloud-init

    # Dependencies
    - ca-certificates
    - software-properties-common
    - curl

    # Adds dbus-launch; needed for changing gsettings through autoinstall
    - dbus-x11

    # GitHub login
    - gh

  # Install basic snap packages
  snaps:
    - name: gnome-3-38-2004
    - name: gtk-common-themes
    - name: snap-store
    - name: snapd-desktop-integration 
  
  user-data:
    runcmd:
      # Add folders, with the right permissions, for Zen Install
      - sudo -u workstation dbus-run-session -- mkdir -p /home/workstation/.local/bin/share/applications
      - export HOME=/home/workstation

      # Install Zen
      - curl -fsSL https://updates.zen-browser.app/install.sh | bash

      # Source ROS2 on terminal startup
      - echo "# Source ROS2\n\nsource /opt/ros/${ROS_CODENAME}/setup.bash" >> /home/workstation/.bashrc

      # Source Phoenix6
      - echo "\n# Source Phoenix6\nexport LD_LIBRARY_PATH=/usr/lib/phoenix6/lib:$LD_LIBRARY_PATH" >> /home/workstation/.bashrc"

      # Set dark mode by default
      - sudo -u workstation dbus-launch gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
      
      # Pin apps to dash
      - sudo -u workstation dbus-launch gsettings set org.gnome.shell favorite-apps "['zen.desktop', 'org.gnome.Terminal.desktop', 'code.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Settings.desktop']"
    
  late-commands:
    # Change display resolution in GRUB
    - >-
      curtin in-target --
      sed -i /etc/default/grub -e
      's/GRUB_CMDLINE_LINUX_DEFAULT=".*/GRUB_CMDLINE_LINUX_DEFAULT="console=tty0 video=${DISP_RES}@120"/'
    - curtin in-target -- update-grub

    # Let NetworkManager handle network -- Only Needed for <= Ubuntu 22.04
    - >-
      printf "network:\n  version: 2\n  renderer: NetworkManager"
      > /target/etc/netplan/01-network-manager-all.yaml

    # Remove ubuntu-server only packages
    - >-
      curtin in-target -- apt-get remove -y
      btrfs-progs cryptsetup* lvm2 xfsprogs
      ubuntu-server ubuntu-server-minimal
      binutils byobu dmeventd finalrd gawk
      kpartx mdadm ncurses-term needrestart open-iscsi openssh-server
      sg3-utils ssh-import-id sssd thin-provisioning-tools vim
      sosreport screen open-vm-tools motd-news-config lxd-agent-loader
      landscape-common fonts-ubuntu-console

    # Disable systemd-networkd
    - curtin in-target -- systemctl stop systemd-networkd
    - curtin in-target -- systemctl disable systemd-networkd
    - curtin in-target -- systemctl mask systemd-networkd.service

    - curtin in-target -- systemctl enable NetworkManager.service
    - curtin in-target -- systemctl start NetworkManager.service

    # Install VSCode
    - curtin in-target -- wget -O /tmp/vscode.deb "https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-arm64"
    - curtin in-target -- dpkg -i /tmp/vscode.deb

    # Install ROS2
    - curtin in-target -- add-apt-repository universe
    - curtin in-target -- curl -L -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.${UBUNTU_CODENAME}_all.deb"
    - curtin in-target -- dpkg -i /tmp/ros2-apt-source.deb
    - curtin in-target -- apt-get update && apt-get upgrade -y
    - curtin in-target -- apt-get install -y ros-${ROS_CODENAME}-desktop

    # Install PlatformIO
    - curtin in-target -- apt-get update
    - curtin in-target -- apt-get install -y pipx 
    - curtin in-target -- pipx install platformio
    - curtin in-target -- pipx ensurepath

    ## ROS 2 control stack
    - >-
      curtin in-target -- apt-get install -y
      ros-${ROS_CODENAME}-ros2-control
      ros-${ROS_CODENAME}-ros2-controllers
      libserial-dev
      ros-${ROS_CODENAME}-twist-mux
    
    ## ROS–Gazebo integration
    - >-
      curtin in-target -- apt-get install -y
      ros-${ROS_CODENAME}-ros-gz
      ros-${ROS_CODENAME}-gz-ros2-control
      ros-${ROS_CODENAME}-xacro
      ros-${ROS_CODENAME}-joint-state-publisher-gui
      ros-${ROS_CODENAME}-robot-state-publisher
      ros-${ROS_CODENAME}-foxglove-bridge
    
    ## Network package
    - curtin in-target -- apt-get install -y ros-${ROS_CODENAME}-rmw-zenoh-cpp
  
    ## Hardware & Sensors
    - >-
      curtin in-target -- apt-get install -y
      ros-${ROS_CODENAME}-joy
      ros-${ROS_CODENAME}-joy-teleop
      ros-${ROS_CODENAME}-realsense2-camera
      ros-${ROS_CODENAME}-realsense2-description
    
    ## Autonomy & Navigation
    - >-
      curtin in-target -- apt-get install -y
      ros-${ROS_CODENAME}-behaviortree-cpp
      ros-${ROS_CODENAME}-navigation2
      ros-${ROS_CODENAME}-nav2-bringup
      ros-${ROS_CODENAME}-slam-toolbox
      ros-${ROS_CODENAME}-robot-localization
      ros-${ROS_CODENAME}-apriltag-ros
    
    ## MOLA SLAM
    - >-
      curtin in-target -- apt-get install -y
      ros-${ROS_CODENAME}-mola
      ros-${ROS_CODENAME}-mola-state-estimation
      ros-${ROS_CODENAME}-mola-lidar-odometry

    # Phoenix6
    - curtin in-target -- curl -s --compressed -o /usr/share/keyrings/ctr-pubkey.gpg "https://deb.ctr-electronics.com/ctr-pubkey.gpg"
    - curtin in-target -- curl -s --compressed -o /etc/apt/sources.list.d/ctr2026.list "https://deb.ctr-electronics.com/ctr2026.list"
    - curtin in-target -- sed -i 's/signed-by=/arch=arm64 signed-by=/' /etc/apt/sources.list.d/ctr2026.list
    - curtin in-target -- apt-get update
    - curtin in-target -- apt-get install -y phoenix6

    # Extra Python Tools
    - curtin in-target -- apt-get install -y python3-colcon-common-extensions python3-rosdep python3-vcstool

  storage:
    layout:
      name: default